### ISSUE TITLE
Complete all testing paths

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/fpga-interchange-tests#25]
At the moment, there are still three testing paths that are not covered (arrows in red in the [testing diagram](https://docs.google.com/drawings/d/12SjkmrsoI-Me4feKJoUV5F_0cfH75AoWoEqyvfI2Uuw/edit)).

These paths are:
- [x] Full vendor tool flow
- [x] bit2fasm
- [x] Comparison between FASM files

**Comment by mithro** [comment]
![FPGA Interchange Testing Flow](https://user-images.githubusercontent.com/21212/122110846-dc22e500-cdd3-11eb-89b4-797062658e92.png)

**Comment by acomodi** [comment]
This has been fixed with https://github.com/SymbiFlow/fpga-interchange-tests/pull/32 and https://github.com/SymbiFlow/fpga-interchange-tests/pull/28. Closing
