### ISSUE TITLE
Add prjoxide from conda

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/fpga-interchange-tests#34]
At the moment `prjoxide` needs to be built, rather than taken from a package manager (conda in this case). Given that the capnproto dependency is quite problematic to handle correctly, there was the need to add a build step for it as well.

As soon as prjoxide is available on [conda](https://github.com/hdl/conda-eda/pull/116), prjoxide should, by default come from conda, therefore allowing to remove the [capnproto build](https://github.com/SymbiFlow/fpga-interchange-tests/blob/98dd8e05528174f3066dcf22ffff45d87d93e52f/Makefile#L29-L41) as well as the [prjoxide build](https://github.com/SymbiFlow/fpga-interchange-tests/blob/98dd8e05528174f3066dcf22ffff45d87d93e52f/Makefile#L48-L52) steps.

**Comment by gatecat** [comment]
Done in #38
